# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  lint-kotlin:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/cucumber-kotlin
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: echo "do lint things here"

  lint-gherkin:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/cucumber-kotlin
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: echo "do lint things here"

  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/cucumber-kotlin
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: mvn clean install -DskipTests=true

  test:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
        environment:
          ENV: "remote"
          CHROME_BIN: "/usr/bin/google-chrome"
    working_directory: ~/cucumber-kotlin
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: mkdir /target/selenium-reports
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.5.3.jar -log reports/selenium/selenium.log
          background: true
      - run: mvn test
      - store_artifacts:
          path: /target/selenium-reports
      - store_artifacts:
          path: /target/cucumber-reports
      - store_artifacts:
          path: /target/surefire-reports

workflows:
  version: 2
  lint-build-test:
    jobs:
      - lint-kotlin
      - lint-gherkin
      - build:
          requires:
            - lint-kotlin
            - lint-gherkin
      - test:
          requires:
            - build
