# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  lint:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/cucumber-kotlin
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - kotlin-todo:
          - checkout
          - run: echo "do lint things here"
      - gherkin-todo:
          - checkout
          - run: echo "do lint things here"

  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/cucumber-kotlin
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: mvn clean install -DskipTests=true

  test:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    working_directory: ~/cucumber-kotlin
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true
      - run: mvn test

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - test:
          requires:
            - build
