# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  lint:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/cucumber-kotlin
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: echo "do lint things here"

  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/cucumber-kotlin
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: mvn clean install -DskipTests=true

  test:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/cucumber-kotlin
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: mvn test

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - test:
          requires:
            - build
